export export LC_ALL=C #without that, the command mongodump crashes
#the default python distribution
export PYTHON_HOME=$HOME/miniconda
export PATH=$PYTHON_HOME/bin:$PATH
#configuration of the PyRNA library
export PYRNA_HOME=/vagrant
export PYTHONPATH=$PYTHONPATH:$PYRNA_HOME
export PATH=$PYRNA_HOME/pyrna/:$PYRNA_HOME/files/grid_tasks/:$PYRNA_HOME/files/scripts/python/:$PYRNA_HOME/files/scripts/shell/:$PATH

alias ls='ls --color'
